name: Run Trading Bot

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'  # اجرای هر ساعت

jobs:
  run_bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Upgrade pip and install dependencies
        run: |
          pip install --upgrade pip setuptools wheel
          pip install numpy==1.26.4 cython
          pip install pandas ccxt mplfinance
          pip install git+https://github.com/TradingStrategyAI/zigzag

      - name: Run Script
        run: python main.py  # اجرای اسکریپت اصلی
