name: Run Python Script

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.4'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          pip install --no-cache-dir ccxt pandas numpy mplfinance
          sudo apt-get update
          sudo apt-get install git -y
          pip install --no-cache-dir git+https://github.com/TradingStrategyAI/zigzag.git

      - name: Run Script
        run: python main.py
