name: Run Trading Script

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 * * * *"  # اجرا در ابتدای هر ساعت

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install --upgrade pip setuptools wheel
          pip install --no-cache-dir numpy cython
          pip install --no-build-isolation zigzag==0.2.2 || pip install git+https://github.com/TradingStrategyAI/zigzag
          pip install ccxt pandas mplfinance

      - name: Run script
        run: main.py
